### PR TITLE
Rewrite the kubernetes charts to not require multiple steps

### PR DESCRIPTION
**Pull request by eco-JoshuaJackson**
Why do we need this change?
=======================
The documentation talks about launching one container then after it
completes launching another. Instead of doing that leverage the ability
to run initcontainers that run before the main application. As we only
have one base container we need to extend logic in the docker-entrypoint
to support these changes

What effects does this change have?
=======================
* Change docker-entrypoint.sh to a modular function based design
** Initialize a db if location is null, so that it can eventually be
externalized via a PVC/other means
* Deletes: kubernetes/nominatim-canary.yaml kubernetes/nominatim.yaml
* Adds a full chart definition that will work for things like helm
* Add default values.yaml
* Creates a deployment with init containers

### CODE REVIEW

**Comment by peter-evans** [comment]
@JoshuaJackson-jobvite Thank you for contributing! This looks great.

I've only looked at the entrypoint briefly so far, but before I spend more time to review and test it I just wanted to check one thing. Have you introduced any behaviour that would be a breaking change to anyone using this image currently? Could someone use this image with the existing deployment strategy outlined in the documentation?

As for the chart, it looks like a good idea. I'm aware of init containers and I vaguely recall playing with them on this project. The trick with changing the postgres data directory looks like it should work fine to distinguish if the container is "init" or not. I might need to spend a bit of time testing the chart, or trying to set up CI to automatically test it.

**Comment by eco-JoshuaJackson** [comment]
Yeah I'd absolutely suggest testing as we're not an gcp site so I haven't tested fully that it doesn't impact anything on that sync side, but those commands are left untouched other then moving to functions. The data directory change would potentially be a breaking change for folks as it does change the default. There should be no other changes that impact existing behavior. I did try to minimize it to make it as easy of a transition as possible. That's one that could be perhaps kept the same today to avoid that issue for folks as that's geared towards the external db work that this sets up for. As such I'll move it back to the original and add a env variable to pass so that it can be changed. Otherwise the changes should just be neutral. Its just a lot of or organizational changes to make it a bit more object orientated

**Comment by eco-JoshuaJackson** [comment]
k based on the above I've moved the datapath back to the original main and it should work with both the normal and the ability to override the path.

**Comment by eco-JoshuaJackson** [comment]
I've not tested super long running init containers yet as I'm still working towards the external db setup to fully test that for our needs. With the existing tiny test suite I can say it works very well, but importing global/asia/america's it should still just work, just have an insanely long init. We should also consider as part of this updating the Readme.md as this will change the mechanism of the install and long init's will be a normal process when doing the import of any sizable set of data.

**Comment by peter-evans** [comment]
@JoshuaJackson-jobvite Sorry for the slow response. After considering this a bit more, I don't think I'm going to have the time and motivation to learn, test and maintain this long-term. I would like to make a proposal. How about you create a repository, perhaps called `nominatim-k8s-chart`, which contains this Helm chart. I will then link to your repository from the readme to point users at a more modern deployment approach using your chart. Then I think we can just focus on smaller changes to the Docker image to make your chart usable. What do you think?

**Comment by eco-JoshuaJackson** [comment]
Peter,

I sort of figured that this would be the response based on some of your pr comments/issue comments and talked with a few folks internally and we’ll go ahead and move it over to the Open Source side of Jobvite and we can link it to there and we’ll help to try and keep it up to date and current for the community. Give me a few days and I’ll send you over the link to get it into on the github.com/jobvite org. Appreciate your work and in pulling this to our side have updated the Readme to include aa thank you to you for creating the base of what we will help carry forward.

I’ll close out the big changes into the nominatim k8s repo and we’ll work together to take it forward.  As a secondary note do you have a contact with nominatim directly as not sure  if we want to poke ping upstream as well to let them know about this agreed upon change.
[Jobvite logo]<https://www.jobvite.com/>
Joshua Jackson | Director of Engineering
Mobile: 408-373-4334
Email: Joshua.jackson@jobvite-inc.com<mailto:joshua.jackson@jobvite-inc.com>

**Comment by peter-evans** [comment]
I don't have any contact with the folks who maintain Nominatim. I know that someone added this repository to the Nominatim documentation [here](https://github.com/osm-search/Nominatim/blob/master/docs/admin/Installation.md). If you want some visibility you could try raising a PR to add your Helm chart deployment repository to the docs.

**Comment by eco-JoshuaJackson** [comment]
Should now be live and in its final home: https://github.com/Jobvite/nominatim-k8s. Thanks for the support, and your efforts in getting a initial chart created.

**Comment by peter-evans** [comment]
Just to clarify, are you intending to build and publish your own Docker image? Or do you want to collaborate on changes to this image? I don't mind either way.

**Comment by eco-JoshuaJackson** [comment]
It'll take a bit, but think the image production probably is best to stay with the charts right now. Which means that yeah we'll start producing a container, that will probably be based on the lower level docker based images and the pr's against that. Make sense?

**Comment by peter-evans** [comment]
> that will probably be based on the lower level docker based images and the pr's against that

Are you are referring to this PR?
https://github.com/peter-evans/nominatim-docker/pull/26

**Comment by eco-JoshuaJackson** [comment]
Yep that'd be the one

**Comment by eco-JoshuaJackson** [comment]
@peter-evans  time got a bit away from me and had a vacation last week as well. Sorry for my somewhat disappearance. Would like to continue to drive on this and get everything wanted/needed through to get this transition through.

Currently it looks like to me we have the following tasks:

1. Review the https://github.com/peter-evans/nominatim-docker/pull/26 and work through that and get new builds up and available for everyone. We should also probably go from 3.5.1 to 3.5.2 as that's recently released but that's a minor change to the overall code.
2. I'll confirm based on the new images available that I'm able to startup both a inbuilt updated container based on the docker versions we did above for kube based. As well as an external db setup.
3. Once two is tested/validated ensure any changes are in the https://github.com/Jobvite/nominatim-k8s/ repository and its ready to generally go, including updating the ability to add it as a repo to helm directly.
4. from there if we're both happy with it can redirect from this repo to the jobvite version (please do check the readme for the thanks to you for your work here and if there's changes there let me know).
5. I'll work with upstream to submit a patch to the documentation to link to the above repo and not directly to this one here as the move forward with upstream.

Sound like a sane plan?

**Comment by peter-evans** [comment]
@JoshuaJackson-jobvite I think it might be best to publish your own images for Nominatim if you want to support other versions of Ubuntu. I'm afraid that I won't have a lot of time to support and maintain the images in the future and I don't want to hold you back. My understanding is that you want to use an external DB anyway. In that case, you can cut out all of the Postgres setup that you don't need. It might be good for the community to have a well-maintained image that supports an external DB.

**Comment by eco-JoshuaJackson** [comment]
Its an extension of what you built to support in image + external db's as that was one of the requests and there's value for us to have that capability. It sounds like though overall the suggestion you have is "take all the components and take over all ownership of both straight docker based image + kube image" if I'm understanding you correctly as we're talking about item 1 above?

**Comment by peter-evans** [comment]
I'm a bit confused about what functionality you need and what you want to add to support the community. Can I ask you to let me know what are minimum features you need to add to [nominatim-docker](https://github.com/peter-evans/nominatim-docker) to support the Helm chart? We should start with the minimum features that you need first, and then afterwards add further features/changes to support the community. This will help me to support you because it's smaller increments of change that are easy to understand and review.

This PR doesn't feel like an easy place to start to me. https://github.com/peter-evans/nominatim-docker/pull/26
What about this is necessary for the Helm chart to work?
We can add other Ubuntu versions later (which involves a fair amount of work to test, and to hook up multiple versions to [release via CI](https://github.com/peter-evans/nominatim-docker/blob/master/.circleci/config.yml), I don't want to be doing that manually).

**Comment by eco-JoshuaJackson** [comment]
There's a few motivations:

1. Xenial is end of general support at this point and while it'll get some updates still for a bit, probably time to move forward/on from that version
2. Postgres 9.5 is EOL in Feb so that's another issue with the xenial version
3. it grants a relatively easy ability for folks to run a version of postgres that works for their environments. Right now 9.5 is the only selection, with the three images you can run 9.5, 10, or 12 which aligns well with general security policies for software concurrency that you might run (cloud native db's are not a factor due to the design of nominatim's loaded compiled library in the db layer). it also means that folks don't have to run potentially multiple different db versions needlessly.

**Comment by peter-evans** [comment]
So I found some time today to convert the CI of [nominatim-docker](https://github.com/peter-evans/nominatim-docker) to GitHub Actions and pave the way for multiple base images of Ubuntu.

To add a new Ubuntu version for focal, for example:
1. Create a directory called `focal` containing the image and dependent files
2. Add `focal` to the list of base images here: https://github.com/peter-evans/nominatim-docker/blob/master/.github/workflows/ci.yml#L50
   i.e. `base-image: [xenial, focal]`

It would be helpful if you can take what you have started in https://github.com/peter-evans/nominatim-docker/pull/26 and get it to build in your fork before raising a PR.

Publishing is disabled for now and the publish step won't execute in pull requests anyway, so you should be able to safely test by enabling GitHub actions for your fork.
https://github.com/peter-evans/nominatim-docker/blob/master/.github/workflows/ci.yml#L95-L100

**Comment by eco-JoshuaJackson** [comment]
Peter,

I think that's more than reasonable and I'd actually started down the path of getting it working with github actions so your work will accelerate it. Appreciate your consideration of the reasons I had mentioned/suggested the needs to support more than one version. I'll rework the PR's for the nominatim-docker this week  as new ones to minimize it to one for focal and one for bionic

**Comment by peter-evans** [comment]
Merged and released images for bionic and focal. Thanks.

**Comment by eco-JoshuaJackson** [comment]
Thanks for the support on this peter. Hopefully next week will be fairly quiet and I can get the rest of the changes verified in the updated k8s and we can take a look at the next steps of the migration from here to the https://github.com/Jobvite/nominatim-k8s/ as per much of the discussion here. 

Again appreciate the time you/your work has allowed you to work with me/us on this and for what you did to make this a reality.

**Comment by eco-JoshuaJackson** [comment]
Closing this as while jobvite did update/create a fork off this in our public space with some updates. It's also fallen behind from what nominatim has done upstream with the complete db installation etc changes. So both this pr and the fork we had created are not current to the new designs. Ultimately probably need someone who has a longer vested interest in nominatim to come in and help drive the support on this, or work with the open street maps/nominatim team to pull it in house.

**Pull request closed without merging**
